configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dagster-labs%2Fdagster-plus-rest-3f53ae0381b01bd6c51ada5d739405c1e8e9b1a99549ce44ac78d133a71d0973.yml
